name: SAP-GitHub Integration Playbook
description: A comprehensive guide for SAP and GitHub Enterprise integration
url: https://three-horizon.github.io
baseurl: /SAP-GitHub-Integration-Playbook

# Basic static site settings
is_static: true
disable_jekyll: true
use_direct_paths: true

# Repository information
repository_url: https://github.com/three-horizon/SAP-GitHub-Integration-Playbook
raw_content_url: https://raw.githubusercontent.com/three-horizon/SAP-GitHub-Integration-Playbook/main

# Image paths for static site
image_base_path: https://raw.githubusercontent.com/three-horizon/SAP-GitHub-Integration-Playbook/main/assets/images 