theme: jekyll-theme-cayman
title: SAP-GitHub Integration Playbook
description: A comprehensive guide for SAP and GitHub Enterprise integration
show_downloads: true
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE

# Liquid configuration to prevent parsing errors with GitHub Actions syntax
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/three-horizon/SAP-GitHub-Integration-Playbook
  repository_name: SAP-GitHub-Integration-Playbook 