theme: jekyll-theme-cayman
title: SAP-GitHub Integration Playbook
description: Comprehensive guide for integrating SAP systems with GitHub Enterprise
show_downloads: true
baseurl: /SAP-GitHub-Integration-Playbook
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-titles-from-headings
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE
  - assets/images/**/*
  - _includes/**/*
  - assets/css/**/*
  - index.html

# Liquid configuration to prevent parsing errors with GitHub Actions syntax
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: false

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/three-horizon/SAP-GitHub-Integration-Playbook
  repository_name: SAP-GitHub-Integration-Playbook

# Add defaults for all pages
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      css: 
        - /assets/css/style.css

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

collections:
  architecture:
    output: true
    permalink: /:collection/:name
  implementation:
    output: true
    permalink: /:collection/:name
  developer:
    output: true
    permalink: /:collection/:name
  operations:
    output: true
    permalink: /:collection/:name
  reference:
    output: true
    permalink: /:collection/:name

# Exclude specific files from being processed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - examples/README.md 