name: CI Playbook Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add steps to lint Markdown files, YAML files, scripts, etc.
      - name: Lint Markdown
        run: echo "Placeholder for Markdown linting"
      - name: Lint YAML
        run: echo "Placeholder for YAML linting"

  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add steps to validate example configurations or run basic tests
      - name: Validate Example Configs
        run: echo "Placeholder for validating example files"
        
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress '**/*.md' '**/*.html'
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
